database:
  driver_name: postgres
  host: xxx
  port: xxx
  dbname: xxx
  user: xxx
  password: xxx
  connect_timeout: 10

# service 管理，服务器认证信息
sshcline:
  private_key: ~/.ssh/id_rsa
  username: xxx
  port: xxx

cron:
  update_server_list: '@every 12h'
  update_service: '@every 3h'
  update_pwd_expired: '0 0 0 * * *'

# 登录认证 LDAP
authentication:
  ldap:
    address: xxx
    port: 389
    basedn: "dc=growingio,dc=com"
    bindusername: "cn=growingio,cn=users,dc=growingio,dc=com"
    bindpassword: xxx

# mail
mail:
  domain: growingio.com
  host: smtp.qiye.163.com
  port: 587
  username: noreply@growingio.com
  password: xxx
